# Donkey Kong Junior Basys3 port driver.
# Usage: make <target>. Run `make help` for available targets.
#
# This port wraps dkongjr_top.v (MiSTer-devel Verilog core, gaz68's Donkey
# Kong Junior port) directly -- the pristine HPS/OSD/HDMI framework
# (Arcade-DonkeyKongJunior.sv, sys/*) is not imported. ROMs are baked into
# BRAM at synthesis time (a single proms/dkongjr_roms.v, generated by a
# host-side Python script -- no gcc needed). The pristine src/ is kept
# untouched: the Vivado project imports src/ minus the dead-code CPU
# alternative and the pristine ROM module (see PORTING_SPEC.md), plus
# contrib/basys3/rtl/'s portable dual-port RAM, PS/2 keyboard chain, and
# scandoubler. See contrib/basys3/vivado/create_project.sh and
# PORTING_SPEC.md.
#
# Default target: build the whole scripted Basys3 port tree.

TOOLS        := contrib/tools
BASYS3_TOOLS := contrib/basys3/tools
VIVADO       := contrib/basys3/vivado

.PHONY: all setup create_prj clk_wiz patch synth bitstream clean help

all: setup clk_wiz patch

setup:
	$(TOOLS)/setup_dkongjr.sh

create_prj: setup
	$(VIVADO)/create_project.sh

clk_wiz: create_prj
	$(VIVADO)/make_clk_wiz_0.sh

patch: setup
	$(BASYS3_TOOLS)/make_dkongjr_basys3_top.sh

synth: clk_wiz patch
	$(BASYS3_TOOLS)/make_dkongjr_basys3_bitstream.sh synth

bitstream: synth
	$(BASYS3_TOOLS)/make_dkongjr_basys3_bitstream.sh bitstream

clean:
	rm -rf basys3 roms proms

help:
	@echo "Donkey Kong Junior Basys3 port driver."
	@echo "Usage: make <target>"
	@echo
	@echo "  all         setup clk_wiz patch (default)"
	@echo "  setup       stage romset + generate proms/dkongjr_roms.v (drop-in dkongjr_rom)"
	@echo "  create_prj  create Vivado project (imports src/ minus dead-code CPU alt + proms)"
	@echo "  clk_wiz     generate clk_wiz_0 MMCM IP (100 -> 24.576 MHz)"
	@echo "  patch       author dkongjr_basys3.vhd top level"
	@echo "  synth       synthesis only (resets synth_1 first)"
	@echo "  bitstream   implementation + write_bitstream"
	@echo "  clean       remove Vivado project tree + staged roms/dkongjr_roms.v"